# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DepthReaderOCR
                                 A QGIS plugin
 Automatically extracts depth values from nautical charts using OCR.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-06-23
        copyright            : (C) 2025 by Elivaldo Rocha
        email                : carvalhovaldo09@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DepthReaderOCR class from file DepthReaderOCR.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .deep_reader_ocr import DepthReaderOCR
    return DepthReaderOCR(iface)
